import type { Country } from './types';

export const COUNTRIES: Country[] = [
    { name: 'Afghanistan', code: 'AF', sub: 'worldnews' },
    { name: 'Aland Islands', code: 'AX', sub: 'worldnews' },
    { name: 'Albania', code: 'AL', sub: 'albania' },
    { name: 'Algeria', code: 'DZ', sub: 'algeria' },
    { name: 'American Samoa', code: 'AS', sub: 'worldnews' },
    { name: 'Andorra', code: 'AD', sub: 'worldnews' },
    { name: 'Angola', code: 'AO', sub: 'worldnews' },
    { name: 'Anguilla', code: 'AI', sub: 'worldnews' },
    { name: 'Antarctica', code: 'AQ', sub: 'worldnews' },
    { name: 'Antigua and Barbuda', code: 'AG', sub: 'worldnews' },
    { name: 'Argentina', code: 'AR', sub: 'argentina' },
    { name: 'Armenia', code: 'AM', sub: 'armenia' },
    { name: 'Aruba', code: 'AW', sub: 'worldnews' },
    { name: 'Australia', code: 'AU', sub: 'australia' },
    { name: 'Austria', code: 'AT', sub: 'austria' },
    { name: 'Azerbaijan', code: 'AZ', sub: 'azerbaijan' },
    { name: 'Bahamas', code: 'BS', sub: 'worldnews' },
    { name: 'Bahrain', code: 'BH', sub: 'bahrain' },
    { name: 'Bangladesh', code: 'BD', sub: 'bangladesh' },
    { name: 'Barbados', code: 'BB', sub: 'worldnews' },
    { name: 'Belarus', code: 'BY', sub: 'belarus' },
    { name: 'Belgium', code: 'BE', sub: 'belgium' },
    { name: 'Belize', code: 'BZ', sub: 'worldnews' },
    { name: 'Benin', code: 'BJ', sub: 'worldnews' },
    { name: 'Bermuda', code: 'BM', sub: 'worldnews' },
    { name: 'Bhutan', code: 'BT', sub: 'worldnews' },
    { name: 'Bolivia', code: 'BO', sub: 'bolivia' },
    { name: 'Bonaire, Sint Eustatius and Saba', code: 'BQ', sub: 'worldnews' },
    { name: 'Bosnia and Herzegovina', code: 'BA', sub: 'bosnia' },
    { name: 'Botswana', code: 'BW', sub: 'worldnews' },
    { name: 'Bouvet Island', code: 'BV', sub: 'worldnews' },
    { name: 'Brazil', code: 'BR', sub: 'brasil' },
    { name: 'British Indian Ocean Territory', code: 'IO', sub: 'worldnews' },
    { name: 'Brunei Darussalam', code: 'BN', sub: 'brunei' },
    { name: 'Bulgaria', code: 'BG', sub: 'bulgaria' },
    { name: 'Burkina Faso', code: 'BF', sub: 'worldnews' },
    { name: 'Burundi', code: 'BI', sub: 'worldnews' },
    { name: 'Cambodia', code: 'KH', sub: 'worldnews' },
    { name: 'Cameroon', code: 'CM', sub: 'worldnews' },
    { name: 'Canada', code: 'CA', sub: 'canada' },
    { name: 'Cape Verde', code: 'CV', sub: 'worldnews' },
    { name: 'Cayman Islands', code: 'KY', sub: 'worldnews' },
    { name: 'Central African Republic', code: 'CF', sub: 'worldnews' },
    { name: 'Chad', code: 'TD', sub: 'worldnews' },
    { name: 'Chile', code: 'CL', sub: 'chile' },
    { name: 'China', code: 'CN', sub: 'china' },
    { name: 'Christmas Island', code: 'CX', sub: 'worldnews' },
    { name: 'Cocos (Keeling) Islands', code: 'CC', sub: 'worldnews' },
    { name: 'Colombia', code: 'CO', sub: 'colombia' },
    { name: 'Comoros', code: 'KM', sub: 'worldnews' },
    { name: 'Congo', code: 'CG', sub: 'worldnews' },
    { name: 'Congo, Democratic Republic of the', code: 'CD', sub: 'worldnews' },
    { name: 'Cook Islands', code: 'CK', sub: 'worldnews' },
    { name: 'Costa Rica', code: 'CR', sub: 'costarica' },
    { name: 'Cote D\'Ivoire', code: 'CI', sub: 'worldnews' },
    { name: 'Croatia', code: 'HR', sub: 'croatia' },
    { name: 'Cuba', code: 'CU', sub: 'cuba' },
    { name: 'Curacao', code: 'CW', sub: 'worldnews' },
    { name: 'Cyprus', code: 'CY', sub: 'cyprus' },
    { name: 'Czech Republic', code: 'CZ', sub: 'czech' },
    { name: 'Denmark', code: 'DK', sub: 'denmark' },
    { name: 'Djibouti', code: 'DJ', sub: 'worldnews' },
    { name: 'Dominica', code: 'DM', sub: 'worldnews' },
    { name: 'Dominican Republic', code: 'DO', sub: 'republicadominicana' },
    { name: 'Ecuador', code: 'EC', sub: 'ecuador' },
    { name: 'Egypt', code: 'EG', sub: 'egypt' },
    { name: 'El Salvador', code: 'SV', sub: 'elsalvador' },
    { name: 'Equatorial Guinea', code: 'GQ', sub: 'worldnews' },
    { name: 'Eritrea', code: 'ER', sub: 'worldnews' },
    { name: 'Estonia', code: 'EE', sub: 'estonia' },
    { name: 'Ethiopia', code: 'ET', sub: 'ethiopia' },
    { name: 'Falkland Islands (Malvinas)', code: 'FK', sub: 'worldnews' },
    { name: 'Faroe Islands', code: 'FO', sub: 'worldnews' },
    { name: 'Fiji', code: 'FJ', sub: 'fiji' },
    { name: 'Finland', code: 'FI', sub: 'finland' },
    { name: 'France', code: 'FR', sub: 'france' },
    { name: 'French Guiana', code: 'GF', sub: 'worldnews' },
    { name: 'French Polynesia', code: 'PF', sub: 'worldnews' },
    { name: 'French Southern Territories', code: 'TF', sub: 'worldnews' },
    { name: 'Gabon', code: 'GA', sub: 'worldnews' },
    { name: 'Gambia', code: 'GM', sub: 'worldnews' },
    { name: 'Georgia', code: 'GE', sub: 'georgia' },
    { name: 'Germany', code: 'DE', sub: 'germany' },
    { name: 'Ghana', code: 'GH', sub: 'ghana' },
    { name: 'Gibraltar', code: 'GI', sub: 'worldnews' },
    { name: 'Greece', code: 'GR', sub: 'greece' },
    { name: 'Greenland', code: 'GL', sub: 'greenland' },
    { name: 'Grenada', code: 'GD', sub: 'worldnews' },
    { name: 'Guadeloupe', code: 'GP', sub: 'worldnews' },
    { name: 'Guam', code: 'GU', sub: 'worldnews' },
    { name: 'Guatemala', code: 'GT', sub: 'guatemala' },
    { name: 'Guernsey', code: 'GG', sub: 'worldnews' },
    { name: 'Guinea', code: 'GN', sub: 'worldnews' },
    { name: 'Guinea-Bissau', code: 'GW', sub: 'worldnews' },
    { name: 'Guyana', code: 'GY', sub: 'worldnews' },
    { name: 'Haiti', code: 'HT', sub: 'haiti' },
    { name: 'Heard Island and Mcdonald Islands', code: 'HM', sub: 'worldnews' },
    { name: 'Holy See (Vatican City State)', code: 'VA', sub: 'worldnews' },
    { name: 'Honduras', code: 'HN', sub: 'honduras' },
    { name: 'Hong Kong', code: 'HK', sub: 'hongkong' },
    { name: 'Hungary', code: 'HU', sub: 'hungary' },
    { name: 'Iceland', code: 'IS', sub: 'iceland' },
    { name: 'India', code: 'IN', sub: 'india' },
    { name: 'Indonesia', code: 'ID', sub: 'indonesia' },
    { name: 'Iran, Islamic Republic of', code: 'IR', sub: 'iran' },
    { name: 'Iraq', code: 'IQ', sub: 'iraq' },
    { name: 'Ireland', code: 'IE', sub: 'ireland' },
    { name: 'Isle of Man', code: 'IM', sub: 'worldnews' },
    { name: 'Israel', code: 'IL', sub: 'israel' },
    { name: 'Italy', code: 'IT', sub: 'italy' },
    { name: 'Jamaica', code: 'JM', sub: 'jamaica' },
    { name: 'Japan', code: 'JP', sub: 'japan' },
    { name: 'Jersey', code: 'JE', sub: 'worldnews' },
    { name: 'Jordan', code: 'JO', sub: 'jordan' },
    { name: 'Kazakhstan', code: 'KZ', sub: 'kazakhstan' },
    { name: 'Kenya', code: 'KE', sub: 'kenya' },
    { name: 'Kiribati', code: 'KI', sub: 'worldnews' },
    { name: 'Korea, Democratic People\'s Republic of', code: 'KP', sub: 'northkorea' },
    { name: 'Korea, Republic of', code: 'KR', sub: 'southkorea' },
    { name: 'Kosovo', code: 'XK', sub: 'kosovo' },
    { name: 'Kuwait', code: 'KW', sub: 'kuwait' },
    { name: 'Kyrgyzstan', code: 'KG', sub: 'worldnews' },
    { name: 'Lao People\'s Democratic Republic', code: 'LA', sub: 'worldnews' },
    { name: 'Latvia', code: 'LV', sub: 'latvia' },
    { name: 'Lebanon', code: 'LB', sub: 'lebanon' },
    { name: 'Lesotho', code: 'LS', sub: 'worldnews' },
    { name: 'Liberia', code: 'LR', sub: 'worldnews' },
    { name: 'Libyan Arab Jamahiriya', code: 'LY', sub: 'libya' },
    { name: 'Liechtenstein', code: 'LI', sub: 'worldnews' },
    { name: 'Lithuania', code: 'LT', sub: 'lithuania' },
    { name: 'Luxembourg', code: 'LU', sub: 'luxembourg' },
    { name: 'Macao', code: 'MO', sub: 'worldnews' },
    { name: 'Macedonia, the Former Yugoslav Republic of', code: 'MK', sub: 'macedonia' },
    { name: 'Madagascar', code: 'MG', sub: 'worldnews' },
    { name: 'Malawi', code: 'MW', sub: 'worldnews' },
    { name: 'Malaysia', code: 'MY', sub: 'malaysia' },
    { name: 'Maldives', code: 'MV', sub: 'maldives' },
    { name: 'Mali', code: 'ML', sub: 'worldnews' },
    { name: 'Malta', code: 'MT', sub: 'malta' },
    { name: 'Marshall Islands', code: 'MH', sub: 'worldnews' },
    { name: 'Martinique', code: 'MQ', sub: 'worldnews' },
    { name: 'Mauritania', code: 'MR', sub: 'worldnews' },
    { name: 'Mauritius', code: 'MU', sub: 'mauritius' },
    { name: 'Mayotte', code: 'YT', sub: 'worldnews' },
    { name: 'Mexico', code: 'MX', sub: 'mexico' },
    { name: 'Micronesia, Federated States of', code: 'FM', sub: 'worldnews' },
    { name: 'Moldova, Republic of', code: 'MD', sub: 'moldova' },
    { name: 'Monaco', code: 'MC', sub: 'worldnews' },
    { name: 'Mongolia', code: 'MN', sub: 'mongolia' },
    { name: 'Montenegro', code: 'ME', sub: 'montenegro' },
    { name: 'Montserrat', code: 'MS', sub: 'worldnews' },
    { name: 'Morocco', code: 'MA', sub: 'morocco' },
    { name: 'Mozambique', code: 'MZ', sub: 'mozambique' },
    { name: 'Myanmar', code: 'MM', sub: 'myanmar' },
    { name: 'Namibia', code: 'NA', sub: 'namibia' },
    { name: 'Nauru', code: 'NR', sub: 'worldnews' },
    { name: 'Nepal', code: 'NP', sub: 'nepal' },
    { name: 'Netherlands', code: 'NL', sub: 'netherlands' },
    { name: 'Netherlands Antilles', code: 'AN', sub: 'worldnews' },
    { name: 'New Caledonia', code: 'NC', sub: 'worldnews' },
    { name: 'New Zealand', code: 'NZ', sub: 'newzealand' },
    { name: 'Nicaragua', code: 'NI', sub: 'nicaragua' },
    { name: 'Niger', code: 'NE', sub: 'worldnews' },
    { name: 'Nigeria', code: 'NG', sub: 'nigeria' },
    { name: 'Niue', code: 'NU', sub: 'worldnews' },
    { name: 'Norfolk Island', code: 'NF', sub: 'worldnews' },
    { name: 'Northern Mariana Islands', code: 'MP', sub: 'worldnews' },
    { name: 'Norway', code: 'NO', sub: 'norway' },
    { name: 'Oman', code: 'OM', sub: 'oman' },
    { name: 'Pakistan', code: 'PK', sub: 'pakistan' },
    { name: 'Palau', code: 'PW', sub: 'worldnews' },
    { name: 'Palestinian Territory, Occupied', code: 'PS', sub: 'palestine' },
    { name: 'Panama', code: 'PA', sub: 'panama' },
    { name: 'Papua New Guinea', code: 'PG', sub: 'worldnews' },
    { name: 'Paraguay', code: 'PY', sub: 'paraguay' },
    { name: 'Peru', code: 'PE', sub: 'peru' },
    { name: 'Philippines', code: 'PH', sub: 'philippines' },
    { name: 'Pitcairn', code: 'PN', sub: 'worldnews' },
    { name: 'Poland', code: 'PL', sub: 'poland' },
    { name: 'Portugal', code: 'PT', sub: 'portugal' },
    { name: 'Puerto Rico', code: 'PR', sub: 'puertorico' },
    { name: 'Qatar', code: 'QA', sub: 'qatar' },
    { name: 'Reunion', code: 'RE', sub: 'worldnews' },
    { name: 'Romania', code: 'RO', sub: 'romania' },
    { name: 'Russian Federation', code: 'RU', sub: 'russia' },
    { name: 'Rwanda', code: 'RW', sub: 'rwanda' },
    { name: 'Saint Barthelemy', code: 'BL', sub: 'worldnews' },
    { name: 'Saint Helena', code: 'SH', sub: 'worldnews' },
    { name: 'Saint Kitts and Nevis', code: 'KN', sub: 'worldnews' },
    { name: 'Saint Lucia', code: 'LC', sub: 'worldnews' },
    { name: 'Saint Martin', code: 'MF', sub: 'worldnews' },
    { name: 'Saint Pierre and Miquelon', code: 'PM', sub: 'worldnews' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC', sub: 'worldnews' },
    { name: 'Samoa', code: 'WS', sub: 'worldnews' },
    { name: 'San Marino', code: 'SM', sub: 'worldnews' },
    { name: 'Sao Tome and Principe', code: 'ST', sub: 'worldnews' },
    { name: 'Saudi Arabia', code: 'SA', sub: 'saudiarabia' },
    { name: 'Senegal', code: 'SN', sub: 'senegal' },
    { name: 'Serbia', code: 'RS', sub: 'serbia' },
    { name: 'Serbia and Montenegro', code: 'CS', sub: 'worldnews' },
    { name: 'Seychelles', code: 'SC', sub: 'worldnews' },
    { name: 'Sierra Leone', code: 'SL', sub: 'worldnews' },
    { name: 'Singapore', code: 'SG', sub: 'singapore' },
    { name: 'Sint Maarten', code: 'SX', sub: 'worldnews' },
    { name: 'Slovakia', code: 'SK', sub: 'slovakia' },
    { name: 'Slovenia', code: 'SI', sub: 'slovenia' },
    { name: 'Solomon Islands', code: 'SB', sub: 'worldnews' },
    { name: 'Somalia', code: 'SO', sub: 'somalia' },
    { name: 'South Africa', code: 'ZA', sub: 'southafrica' },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS', sub: 'worldnews' },
    { name: 'South Sudan', code: 'SS', sub: 'worldnews' },
    { name: 'Spain', code: 'ES', sub: 'spain' },
    { name: 'Sri Lanka', code: 'LK', sub: 'srilanka' },
    { name: 'Sudan', code: 'SD', sub: 'sudan' },
    { name: 'Suriname', code: 'SR', sub: 'worldnews' },
    { name: 'Svalbard and Jan Mayen', code: 'SJ', sub: 'worldnews' },
    { name: 'Swaziland', code: 'SZ', sub: 'worldnews' },
    { name: 'Sweden', code: 'SE', sub: 'sweden' },
    { name: 'Switzerland', code: 'CH', sub: 'switzerland' },
    { name: 'Syrian Arab Republic', code: 'SY', sub: 'syria' },
    { name: 'Taiwan, Province of China', code: 'TW', sub: 'taiwan' },
    { name: 'Tajikistan', code: 'TJ', sub: 'worldnews' },
    { name: 'Tanzania, United Republic of', code: 'TZ', sub: 'tanzania' },
    { name: 'Thailand', code: 'TH', sub: 'thailand' },
    { name: 'Timor-Leste', code: 'TL', sub: 'worldnews' },
    { name: 'Togo', code: 'TG', sub: 'worldnews' },
    { name: 'Tokelau', code: 'TK', sub: 'worldnews' },
    { name: 'Tonga', code: 'TO', sub: 'worldnews' },
    { name: 'Trinidad and Tobago', code: 'TT', sub: 'trinidadandtobago' },
    { name: 'Tunisia', code: 'TN', sub: 'tunisia' },
    { name: 'Turkey', code: 'TR', sub: 'turkey' },
    { name: 'Turkmenistan', code: 'TM', sub: 'worldnews' },
    { name: 'Turks and Caicos Islands', code: 'TC', sub: 'worldnews' },
    { name: 'Tuvalu', code: 'TV', sub: 'worldnews' },
    { name: 'Uganda', code: 'UG', sub: 'uganda' },
    { name: 'Ukraine', code: 'UA', sub: 'ukraine' },
    { name: 'United Arab Emirates', code: 'AE', sub: 'dubai' },
    { name: 'United Kingdom', code: 'GB', sub: 'unitedkingdom' },
    { name: 'United States', code: 'US', sub: 'worldnews' },
    { name: 'United States Minor Outlying Islands', code: 'UM', sub: 'worldnews' },
    { name: 'Uruguay', code: 'UY', sub: 'uruguay' },
    { name: 'Uzbekistan', code: 'UZ', sub: 'worldnews' },
    { name: 'Vanuatu', code: 'VU', sub: 'worldnews' },
    { name: 'Venezuela', code: 'VE', sub: 'venezuela' },
    { name: 'Viet Nam', code: 'VN', sub: 'vietnam' },
    { name: 'Virgin Islands, British', code: 'VG', sub: 'worldnews' },
    { name: 'Virgin Islands, U.s.', code: 'VI', sub: 'worldnews' },
    { name: 'Wallis and Futuna', code: 'WF', sub: 'worldnews' },
    { name: 'Western Sahara', code: 'EH', sub: 'worldnews' },
    { name: 'Yemen', code: 'YE', sub: 'yemen' },
    { name: 'Zambia', code: 'ZM', sub: 'zambia' },
    { name: 'Zimbabwe', code: 'ZW', sub: 'zimbabwe' }
];

export const FALLBACK_TOPICS = [
  "Global Tech", "Future AI", "Space Exploration", "Green Energy", 
  "Digital Economy", "Scientific Breakthrough"
];
